### ISSUE TITLE
[BUG] A, B, R and D Bands show up as ... in Matches when assigned to pilots

### ISSUE THREAD

**Issue by DownRightFPV** [hydrafpv/roadmap#11]
**Describe the bug**
In the matches tab, if a pilot is assigned a frequency in the A, B, R or D band, their band/channel displays as `...`.  It appears to be only a GUI issue, because when you attempt to select a different channel, the one I intended to set is highlighted.

**To Reproduce**
1. Create an IRL Race (Mini quad in my case)
2. From the Event Config page, set channels in the A, B, R, or D band
3. Add pilots to a match and assign their channels

**Expected behavior**
The band / channel should display

**Screenshots**
![image0](https://user-images.githubusercontent.com/66377885/92664838-eb5f8a00-f2b9-11ea-8dd7-69d157051a5f.jpg)

**Device and Versions (please complete the following information):**
 - Device: iPad Pro 12.9 4th gen
 - iPadOS Version: 13.6.1
 - App Version: 1.62.0 (150)

**Comment by netizen01** [comment]
Y'all are leaving good bug reports. Thanks. :-)

Fixed in 151.
