### ISSUE TITLE
[BUG] Inactive players show up in matches

### ISSUE THREAD

**Issue by DownRightFPV** [hydrafpv/roadmap#12]
**Describe the bug**
Players who have been set to 'inactive' are showing up in the bench area of matches.

**To Reproduce**
1. Create an event
2. Add some players
3. Set one of the players to inactive in the 'players' tab
4. See that the player is still present when creating a match

**Expected behavior**
Inactive players are hidden from the matches

**Device and Versions (please complete the following information):**
 - Device: iPad Pro 12.9 4th gen
 - iPadOS Version: 13.6.1
 - App Version: 1.62.0 (150)

**Comment by greg571** [comment]
I am seeing this issue too.

**Comment by netizen01** [comment]
Nice. Fixed in 151.
