### ISSUE TITLE
[BUG] Build 150 App Crashing in timing

### ISSUE THREAD

**Issue by greg571** [hydrafpv/roadmap#14]
**Describe the bug**
Under the timing tab, clicking the puck icon, the app crashes. Experienced by three different users. Cant configure timer

**To Reproduce**
Go to timing tab
Click Puck Icon

**Device and Versions (please complete the following information):**
Ipad Pro 12" Director build 150

**Additional context**

**Comment by netizen01** [comment]
Yay! Easy! Fixed in 151.
