### ISSUE TITLE
[BUG] Cannot start a match if current time > event start time

### ISSUE THREAD

**Issue by DownRightFPV** [hydrafpv/roadmap#22]
**Describe the bug**
If the current time has not surpassed the time specified for the event to begin in the event configuration, you cannot start a match 

**To Reproduce (not working)**
1. Create an event with a start time later than your current time of day
2. Create a match and set status to active

**To Reproduce (working)**
1. Change the start time to a time before your current time of day
2. Start the match you previously created

**Expected behavior**
I would like to be able to start an event regardless of whether or not the current time has surpassed the event start time.  

**Video**
In this video you will see an event where the start time is > current time.  I attempt to start a match, stop it, change the event time to a time in the past, and then start the same match.
https://youtu.be/VBPzwqS_2qA

**Device and Versions:**
- Device: iPad Pro 12.9 4th gen
- iPadOS Version: 13.6.1
- App Version: 1.62.0 (ANY)

**Comment by netizen01** [comment]
I think this is fixed! Please test!

**Comment by DownRightFPV** [comment]
Works perfect, thank you!
