### ISSUE TITLE
[BUG] Points Not Scoring In Main Rounds

### ISSUE THREAD

**Issue by GWG571** [hydrafpv/roadmap#24]
**Describe the bug**
Running nonbracket main round, timing data is good, but the match does not score points.

**To Reproduce**
Set mains to points low
Run main match and watch timing data come in
End match, Run Scores, and Run Results
Check the match, each pilot has 1 point assigned to them despite timing data showing a finish order.

**Expected behavior**
After running scores and results expecting point data to be saved under the main match. 

**Screenshots**

**Device and Versions (please complete the following information):**
 - Device: iPad 12"
 - iPadOS Version: 13.6.1
 - App Version: 1.62.0 Build 146. Cant' test in 148 and 150 as we can't access timer settings.
 - Director Level: Full beta

**Comment by greg571** [comment]
This past weekend I saw this also happen with brackets. It assigned first to all pilots. If this is user error please advise how we should set it up.

**Comment by GWG571** [comment]
Closing this as it is same as issue 30. Found out that hitting the sort button after a race will cause a main to score points as a temp fix.
