### ISSUE TITLE
[BUG] Unable to add second director to event

### ISSUE THREAD

**Issue by TwitchyFPV** [hydrafpv/roadmap#26]
**Describe the bug**
Cannot add a second director using their email to an event that has been created.

**To Reproduce**
1. Go to "Access Control" event config page
2. Type email of admin
3. Click "+" button

Animated dialog appears showing that it is verifying the admin, and then it says they were added.

**Expected behavior**
I would expect to see the admin show up, but only the creator is listed.

**Screenshots**
<img width="1194" alt="IMG_7666" src="https://user-images.githubusercontent.com/42357482/93722012-9983f300-fb48-11ea-850d-7fde576fe5c5.png">

**Device and Versions (please complete the following information):**
 - Device: iPad Pro (11-inch)
 - iPadOS Version: 13.6.1
 - App Version: 1.62.0 (146 & 150)

**Comment by netizen01** [comment]
Fixed. No update to iPad app required.
