### ISSUE TITLE
[FEATURE REQ] Generate matches with more than 4 players

### ISSUE THREAD

**Issue by DyoGTS** [hydrafpv/roadmap#3]
Currently creating random matches only generate with 4 players - please add the ability to scale this for more players.

Common examples include, 5 pilots for 5" races, 6-7 pilots for sim races, 8 pilots utilizing full Raceband.

**Comment by netizen01** [comment]
Done! It's a bit obtuse, but what you will do is make sure to have setup the frequencies you're using in the Event Setup area. The round generation will now use the number of frequencies as the number of seats per match.
