### ISSUE TITLE
[BUG] Alias Phonetic Name Issues

### ISSUE THREAD

**Issue by GWG571** [hydrafpv/roadmap#36]
**Describe the bug**
If a player has no phonetic name entered, no times are read for that player. Not sure if it's possible for alias phonetic to default to their alias, then we change alias phonetic if there is an need? Also not 100% how to reproduce this, Downright and I have both seen, times where phonetic names are not read in a match for some players. Then in other matches they read just fine. There seems to be no easy way to reproduce, it's random. 

**To Reproduce**
Part one of the issue has been consistent most of the time. No Alias Phonetic, no times read for that player. Second part is intermittent, or we are not sure what the cause it.

**Expected behavior**
If possible if director can use the Alias as the Alias Phonetic until a race director changes Alias Phonetic? As we have found director does not read times with no data in this field.

**Device and Versions (please complete the following information):**
 - Device: 12.5 iPad Pro
 - iPadOS 14.1
 - App Version: Director 1.62.9 (159)
 - Director Level: Full Beta

**Additional context**

**Comment by netizen01** [comment]
I believe this is fixed. Please test!

**Comment by GWG571** [comment]
Yes, looks like it’s fixed now. Just ran a test and had names read out from all pilots. Thanks!

**Comment by DownRightFPV** [comment]
Confirmed fixed for me as well, this was a big one, thanks @netizen01 !
