### ISSUE TITLE
[Feature Request] Restream chat

### ISSUE THREAD

**Issue by DownRightFPV** [hydrafpv/roadmap#38]
It would be great if we had the option to be able to pull restream chat in along with hydra chat.

**Comment by netizen01** [comment]
Exists. :-)
Connect your Restream account in the app.
Pull in the chat pane (swipe in from right side) and then select the sync button (looks like the recycle button top left of the panel).
That should send any chat from Restream over to the Hydra Chat for the event.
--> Hydra chat unfortunately cannot go into Restream at the moment though...

**Comment by DownRightFPV** [comment]
Wow that's awesome.  Thank you for the explanation... I often forget about those side menus
